## Conference

- *On Mandarin-speaking children's acquisition of control structures and raising structures*.
Beijing Foreign University 2023 Conference on Biolinguistics & Language Acquisition.
Beijing Foreign University, Beijing, China, Sep 22, 2023.

- *An experimental study of Mandarin-speaking children's acquisition of recursion under a formal definition/classification system for recursion*.
[Workshop Recursion Across Languages: The Intricacies of Babel](https://lls.unibuc.ro/2021/workshop-recursion-across-languages-the-intricacies-of-babel).
Bucharest, Romania, June 1-2, 2021. (Virtual)

## Talk

- *Mandarin-speaking children's acquisition of relative clauses*.
[UConn Ling Lunch](https://linguistics.uconn.edu/events/lunch).
University of Connecticut, Storrs, CT, USA, Nov 7, 2023.

- *On Mandarin-speaking children's acquisition of control structures and raising structures*.
UMass AcquiLab.
University of Massachusetts, Amherst, MA, USA, Dec 29, 2022.

- *Coordination, embedding and feature sharing of locative proposition in Chinese*.
UMass AcquiLab.
University of Massachusetts, Amherst, MA, USA, Oct 20, 2022.
